// this file is automatically generated by git.version.ts script
export const versions = {
                version: '1.0.0', 
                revision: '0136aaf', 
                branch: 'master',
                fecha: '20190509_184656'
            };